### ISSUE TITLE
Feat: Setup `dwy.is` domain and point to `Hetzner`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/linky#18]
As noted in https://github.com/dwyl/linky/issues/14#issuecomment-1232494407 I registered the domain `dwy.is` last year to use for URL shortening. 🔗 
That was shortly before "crunch time" (when 👶 2️⃣ was born) 
***so*** I didn't get around to building/deploying **`linky`** at the time ... 🤦‍♂️ 

# Todo

+ [ ] Build the `Linky` App _first_: https://github.com/dwyl/linky/issues/13  👨‍💻 
`.then`
+ [ ] Deploy to `Hetzner` and :shipit: 
+ [ ] Login to `Namecheap` 🚪 
+ [ ] Point the DNS to the `Hetzner` app. 🚀 
+ [ ] Document _all_ the steps e.g. in `learn-devops` or `book`. 📝

**Comment by nelsonic** [comment]
https://ap.www.namecheap.com/Domains/DomainControlPanel/dwy.is/advancedns

<img width="1631" alt="Image" src="https://github.com/user-attachments/assets/81e807d9-d22d-4b9a-9e8f-485cf0e343cf" />

**Comment by nelsonic** [comment]
https://dnschecker.org/#A/dwy.is

Not yet propagated ... ⏳ 
Will check back later (or tomorrow...)

**Comment by nelsonic** [comment]
https://dwy.is
<img width="907" alt="Image" src="https://github.com/user-attachments/assets/04efe3f4-7c2b-4045-ad7d-9c917d3f5f3c" />

<img width="907" alt="Image" src="https://github.com/user-attachments/assets/cffe046f-f1a2-400e-b2ae-e4805977250c" />

**Comment by nelsonic** [comment]
Configuring subdomains on Nginx: https://youtu.be/qQl93M7XpJA

> **EDIT**: watched it. Very basic/superficial. Only useful if you've _never_ done this before.
I actually need a _way_ more specific config.

**Comment by nelsonic** [comment]
https://autobase.dwy.is/login
<img width="1052" alt="Image" src="https://github.com/user-attachments/assets/1dba8936-8670-4ab6-a682-9442a0d7affd" />

Wildcard SSL/TLS not working yet because of slow `TXT` propagation. ⏳

**Comment by nelsonic** [comment]
https://ap.www.namecheap.com/domains/domaincontrolpanel/dwy.is/advancedns
![dwyis-txt-record](https://github.com/user-attachments/assets/80ddea19-d06c-4d71-8c8e-f86ee2acd9dc)

https://toolbox.googleapps.com/apps/dig/#TXT/_acme-challenge.dwy.is
![Igoogle-dig-txt](https://github.com/user-attachments/assets/6ccbb156-6c34-4d67-9c13-f69db9b47a76)
